# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenum', models.CharField(max_length=32, null=True, verbose_name='手机号')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
