# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soluation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mobilenum',
            field=models.CharField(max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
