# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-08 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soluation', '0002_auto_20191007_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
