# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tec',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='tec',
            name='like',
            field=models.CharField(max_length=10, verbose_name='like/dislike'),
        ),
    ]
