# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20191023_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tec',
            old_name='like',
            new_name='like1_dislike0',
        ),
    ]
